### PR TITLE
pkgver update, cmake cuda fix, and flann dependency

### PR DESCRIPTION
**Pull request by mgrewe**
Hi, I have made some small fixes. Please consider for merge.
Thanks, Martin

### CODE REVIEW

**Comment by bartoszek** [comment]
Nice, but could we preserve the `CUDA_ARCH` env var. Nice to have an option to force specific compute capabilities when build on a system different form the target one.

**Comment by mgrewe** [comment]
Absolutely, sorry that I missed that. I have adjusted the env var's name to match the CMake option.

**Comment by bartoszek** [comment]
@mgrewe btw. what's your aur handle, would you like to co-maintain the colmap packages?

**Comment by mgrewe** [comment]
Hi @bartoszek . Sorry for the delayed answer, was quite busy last week. I'm happy helping to maintain this package. Find me by mgrewe on AUR.

**Pull request merged**
